### ISSUE TITLE
Arms make players crash online

### ISSUE THREAD

**Issue by Infinity89** [sekwah41/Naruto-Mod#15]
Arms and general animation make other players crash, before the crash arms and legs disappear

**Comment by Infinity89** [comment]
* more in particular, the wall jutsu make other players crash if they watch the animation

**Comment by Infinity89** [comment]
![crash](https://user-images.githubusercontent.com/46850645/52436725-4a28b480-2b15-11e9-9eac-29d6718c618d.png)

**Comment by sekwah41** [comment]
I need the crash log of the client not the disconnect log of the server.

Commonly crash logs will have a keyword such as "caused by". One of the most common errors send usually is a NullPointerException. I need a stack

Example from bukkit

```Java
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerInteractEvent.getHand()Lorg/bukkit/inventory/EquipmentSlot;
at com.sekwah.advancedportals.listeners.Listeners.onItemInteract(Listeners.java:226) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
... 17 more
```

**Comment by sekwah41** [comment]
This allows me to know exactly what code is responsible for the crash if it be an incompatibility with another mod causing unexpected data or an issue I have coded.

**Comment by sekwah41** [comment]
This issue is being closed due to a lack of crash logs and activity

Please test the pre release available here https://discord.gg/fAJ3xJg then if the issue is still persisting comment here with the actual crash log rather than server disconnect message.
