### ISSUE TITLE
Crash log, i need help with this

### ISSUE THREAD

**Issue by Lodock** [sekwah41/Naruto-Mod#235]
I have a problem with the mod, this is the crash log

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-08-25 22:33:04
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.44-universal.jar%23259!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.1.44-universal.jar%23259!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.1.44-universal.jar%23259!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.44.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.44.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.sekwah.narutomod.entity.NarutoEntities.<clinit>(NarutoEntities.java:30) ~[NarutoMod-1.20-1.8.1-deobf.jar%23234!/:?] {re:classloading}
-- MOD narutomod --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.44.jar%23256!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.44.jar%23255!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/user/curseforge/minecraft/Instances/Mods Pack (1)/mods/NarutoMod-1.20-1.8.1-deobf.jar
	Failure message: Sekwah41's Naruto mod (narutomod) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 0.0NONE
	Mod Issue URL: https://github.com/sekwah41/Naruto-Mod/issues
	Exception message: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.EntityType$Builder net.minecraft.world.entity.EntityType$Builder.of(net.minecraft.world.entity.EntityType$EntityFactory, net.minecraft.world.entity.MobCategory)'
Stacktrace:
	at com.sekwah.narutomod.entity.NarutoEntities.<clinit>(NarutoEntities.java:30) ~[NarutoMod-1.20-1.8.1-deobf.jar%23234!/:?] {re:classloading}
	at com.sekwah.narutomod.NarutoMod.<init>(NarutoMod.java:66) ~[NarutoMod-1.20-1.8.1-deobf.jar%23234!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.44.jar%23256!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.44.jar%23255!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 785974784 bytes (749 MiB) / 2155872256 bytes (2056 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700KF
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.61
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38775.27
	Virtual memory used (MB): 34733.73
	Swap memory total (MB): 8481.58
	Swap memory used (MB): 491.58
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Loaded Shaderpack: Nostalgia_v5.0.zip
		Profile: High (+0 options changed by user)
	NEC status: No NEC detected
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.44.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		alchemylib-1.20.1-1.0.29.jar                      |AlchemyLib                    |alchemylib                    |1.0.29              |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.20.1-7.0.0.jar                         |Cucumber Library              |cucumber                      |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		watermedia-1.3.35.jar                             |WaterMedia                    |watermedia                    |1.3.35              |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.2.1.jar                   |GeckoLib 4                    |geckolib                      |4.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		scena-forge-1.0.102.jar                           |Scena                         |scena                         |1.0.102             |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.2.0.jar                   |Botarium                      |botarium                      |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |COMMON_SET|Manifest: NOSIGNATURE
		immersive_aircraft-0.5.2+1.20.1-forge.jar         |Immersive Aircraft            |immersive_aircraft            |0.5.2+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-0.6.5.jar                                |Rubidium                      |rubidium                      |0.6.5               |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.1.jar                   |Waystones                     |waystones                     |14.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.3.jar                  |Clumps                        |clumps                        |12.0.0.3            |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.12-forge.jar                |Journeymap                    |journeymap                    |5.9.12              |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-6.3.3+1.20.1.jar                   |Comforts                      |comforts                      |6.3.3+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.4.2-1.20.1.jar                          |Citadel                       |citadel                       |2.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.22.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.5              |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.43.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.43            |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.8.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.8        |COMMON_SET|Manifest: NOSIGNATURE
		Dungeon Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |COMMON_SET|Manifest: NOSIGNATURE
		starlight-1.1.2+forge.1cda73c.jar                 |Starlight                     |starlight                     |1.1.2+forge.1cda73c |COMMON_SET|Manifest: NOSIGNATURE
		mcw-doors-1.1.0forge-mc1.20.1.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.20-7.0.7.jar                         |Balm                          |balm                          |7.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.238.jar          |Just Enough Resources         |jeresources                   |1.4.0.238           |COMMON_SET|Manifest: NOSIGNATURE
		UsefulSlime-forge-1.20-1.6.0.jar                  |Useful Slime                  |usefulslime                   |1.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		Paraglider-1.20.1-1.9.0.0.jar                     |Paraglider                    |paraglider                    |1.9.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.1.44-universal.jar                |Forge                         |forge                         |47.1.44             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.20.1-4.3.1809-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1809            |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAgriculture-1.20.1-7.0.2.jar              |Mystical Agriculture          |mysticalagriculture           |7.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4.jar                       |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |COMMON_SET|Manifest: NOSIGNATURE
		alchemistry-1.20.1-2.3.3.jar                      |Alchemistry                   |alchemistry                   |2.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.1.1-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
		SekCLib-1.20-1.0.2-universal.jar                  |SekC Lib                      |sekclib                       |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		repurposed_structures-7.1.3+1.20.1-forge.jar      |Repurposed Structures         |repurposed_structures         |7.1.3+1.20.1-forge  |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.20-2.8.7-forge.jar                    |Moonlight Library             |moonlight                     |1.20-2.8.7          |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.597.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.597          |COMMON_SET|Manifest: NOSIGNATURE
		snowyspirit-1.20-2.2.4.jar                        |Snowy Spirit                  |snowyspirit                   |1.20-2.2.4          |COMMON_SET|Manifest: NOSIGNATURE
		NarutoMod-1.20-1.8.1-deobf.jar                    |Sekwah41's Naruto mod         |narutomod                     |0.0NONE             |ERROR     |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.34_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.10.34             |COMMON_SET|Manifest: NOSIGNATURE
		Chunky-1.3.92.jar                                 |Chunky                        |chunky                        |1.3.92              |COMMON_SET|Manifest: NOSIGNATURE
		spectrelib-forge-0.13.12+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.12+1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.0.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.2.0-beta.3+1.20.1.jar              |Curios API                    |curios                        |5.2.0-beta.3+1.20.1 |COMMON_SET|Manifest: NOSIGNATURE
		ars_nouveau-1.20.1-4.2.4-all.jar                  |Ars Nouveau                   |ars_nouveau                   |4.2.4               |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.1-81-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-81-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		oculus-mc1.20-1.6.4.jar                           |Oculus                        |oculus                        |1.6.4               |COMMON_SET|Manifest: NOSIGNATURE
		chemlib-1.20.1-2.0.17.jar                         |ChemLib                       |chemlib                       |2.0.17              |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.10.jar            |Resourceful Lib               |resourcefullib                |2.1.10              |COMMON_SET|Manifest: NOSIGNATURE
		Aquaculture-1.20.1-2.5.0.jar                      |Aquaculture 2                 |aquaculture                   |2.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		smallships-forge-1.20.1-2.0.0-a2.3.3.jar          |Small Ships                   |smallships                    |2.0.0-a2.3.3        |COMMON_SET|Manifest: NOSIGNATURE
		waterframes-1.20.1-1.4.1a.jar                     |WaterFrames                   |waterframes                   |1.4.1a              |COMMON_SET|Manifest: NOSIGNATURE
		chisels-and-bits-forge-1.4.141.jar                |chisels-and-bits              |chiselsandbits                |1.4.141             |COMMON_SET|Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.3.jar                  |Ad Astra                      |ad_astra                      |1.15.3              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 07428588-a711-437e-8a89-7a31d0a64f6f
	FML: 47.1
	Forge: net.minecraftforge:47.1.44

**Comment by sekwah41** [comment]
Strange I do no reflection there. Probably just need to update the mod my end based on dependencies.

**Comment by sekwah41** [comment]
Closing as I haven't seen anyone else with this issue. Sorry I've left this mod for a while.
